# Generated by Django 3.0.6 on 2020-05-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=30)),
                ('nachname', models.CharField(max_length=30)),
                ('geburstag', models.DateField()),
                ('d_ort', models.CharField(max_length=30)),
                ('familienstand', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=30, unique=True)),
                ('adresse', models.CharField(max_length=30)),
                ('hobbys', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sprachen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprache', models.CharField(max_length=20)),
                ('sprachniveau', models.CharField(max_length=30)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvsite.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Kenntnisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kenntniss', models.CharField(max_length=100)),
                ('kn_niveau', models.CharField(max_length=50)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvsite.Data')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cvsite.User'),
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvsite.User')),
            ],
        ),
        migrations.CreateModel(
            name='Beruf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_anfang', models.DateField()),
                ('b_ende', models.DateField()),
                ('b_ort', models.CharField(max_length=100)),
                ('b_beschreibung', models.TextField(blank=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvsite.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Ausbildung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abschluss', models.CharField(max_length=100)),
                ('a_anfang', models.DateField()),
                ('e_ende', models.DateField()),
                ('a_ort', models.CharField(max_length=100)),
                ('a_beschreibung', models.TextField(blank=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvsite.Data')),
            ],
        ),
    ]
