# Generated by Django 3.0.7 on 2020-06-13 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=30)),
                ('familystatus', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=30, unique=True)),
                ('adresse', models.CharField(max_length=30)),
                ('hobbys', models.CharField(max_length=80)),
                ('pic', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('s_level', models.CharField(max_length=50)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvsite.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('language_lvl', models.CharField(max_length=30)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvsite.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_start', models.DateField()),
                ('exp_end', models.DateField()),
                ('exp_place', models.CharField(max_length=100)),
                ('exp_description', models.TextField(blank=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvsite.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=100)),
                ('edu_start', models.DateField()),
                ('edu_end', models.DateField()),
                ('edu_place', models.CharField(max_length=100)),
                ('edu_description', models.TextField(blank=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvsite.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_about', models.CharField(max_length=100)),
                ('template_adresse', models.CharField(max_length=100)),
                ('template_education', models.CharField(max_length=100)),
                ('template_experience', models.CharField(max_length=100)),
                ('template_language', models.CharField(max_length=100)),
                ('template_name', models.CharField(max_length=100)),
                ('template_photo', models.CharField(max_length=100)),
                ('template_skills', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
