# Generated by Django 3.0.7 on 2020-06-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='pic',
            new_name='picture',
        ),
    ]
