# Generated by Django 3.0.5 on 2020-06-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0002_auto_20200630_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cv',
            name='name',
            field=models.CharField(default='unnamed', max_length=30),
        ),
    ]
