# Generated by Django 3.0.7 on 2020-06-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0002_auto_20200613_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='edu_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='edu_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='edu_place',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='edu_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='exp_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='exp_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='exp_place',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='exp_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language_lvl',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='s_level',
            new_name='level',
        ),
    ]
