# Generated by Django 3.0.5 on 2020-06-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0002_cv_cv_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
