# Generated by Django 3.0.5 on 2020-06-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0004_auto_20200630_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
