# Generated by Django 3.0.7 on 2020-06-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0004_auto_20200605_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='user',
        ),
        migrations.RemoveField(
            model_name='data',
            name='user',
        ),
    ]
