# Generated by Django 3.0.5 on 2020-06-30 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0005_auto_20200630_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
