# Generated by Django 3.0.7 on 2020-06-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0005_auto_20200605_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cv',
        ),
    ]
