# Generated by Django 3.0.5 on 2020-06-30 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0006_cv_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
