# Generated by Django 3.0.7 on 2020-06-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0006_delete_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='thumb',
            new_name='pic',
        ),
    ]
