# Generated by Django 3.0.5 on 2020-06-30 04:56

import cvsite.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0007_auto_20200630_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=cvsite.fields.IntegerRangeField(default=0, verbose_name='Level - from 0 - 10'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=cvsite.fields.IntegerRangeField(default=0, verbose_name='Level - from 0 - 10'),
        ),
    ]
