# Generated by Django 3.0.6 on 2020-06-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0003_auto_20200613_1554'),
        ('cvsite', '0008_auto_20200605_1136'),
    ]

    operations = [
    ]
